#pragma once


void funcWithThrow();
void exceptionDemoFunc();